version: "3.3"

services:
  eneftiland:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/eneftiland
      - /eneftiland/node_modules
      - /eneftiland/.next
